name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.1, 1.20.5]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: |
          sudo apt install libasound2-dev
          go test -v -cover ./... -coverprofile coverage.out -coverpkg ./...